---
- name: Install MIPS compiler toolchain
  become: true
  apt:
      name:
      - gcc-mips-linux-gnu
      - binutils-mips-linux-gnu

- name: Let qemu know where the MIPS root is
  become: true
  file:
      dest: /etc/qemu-binfmt/mips
      src: /usr/mips-linux-gnu
      state: link
